# docker-compose up -d
# docker-compose exec ubuntu bash
# docker-compose exec mysql bash

services:  
  mysql:
    image: mysql:latest
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: global_site_db
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  ubuntu:
    image: ubuntu:latest
    volumes:
      - ./setup.sh:/setup.sh
      - ../Global-Site/:/root/Projects/Global-Site/
    command: tail -f /dev/null
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8080:8080"
    depends_on:
      - mysql
  
volumes:
  mysql_data: